### ISSUE TITLE
Consider generating the same Get/IsSet functions as apache thrift

### ISSUE THREAD

**Issue by mvj101** [thriftrw/thriftrw-go#171]
apache thrift generates functions like GetBar() and IsSetBar() for a struct like:

```
struct Foo {
  1: optional string Bar
}
```

If a user is migrating from apache thrift to thriftrw, it may be easier for them to migrate if those same functions are generated by thriftrw.

**Comment by mvj101** [comment]
apache thrift also generates a NewFoo() function and its names for enums are different compared to thriftrw:

for example:

enum PrimitiveType {
  BLOB = 0
}

thriftrw
type PrimitiveType int32
const (
        PrimitiveTypeBlob      PrimitiveType = 0
)

apache thrift
type PrimitiveType int64
const (
  PrimitiveType_BLOB      PrimitiveType = 0
)

**Comment by breerly** [comment]
@abhinav do you think this is useful? I'd like to prioritize customer feedback if possible

**Comment by abhinav** [comment]
Enum naming: I believe (fairly strongly) that our naming scheme is better/more idiomatic for Go and we should keep it. (Also, them generating `int64` is just plain wrong because enums are sent as `int32` over the wire.)

Get and IsSet functions: I'm reluctant to pollute the attribute namespace too much. Attributes and methods of a type share the same namespace, so any method we add there can no longer be an attribute name. You can't have an attributes `foo` and  'getFoo` on the same type if we generate getters. I'm happy to revisit this position if people think we really need it, but IMO getters on plain structs are unnecessary.

FWIW ThriftRW has generally erred on the side of correctness rather than being API compatible with Apache Thrift.

**Comment by breerly** [comment]
@prashantv could we get your wise Go opinion here?

**Comment by breerly** [comment]
Perhaps the right call here is a markdown file that enumerates the differences in generated shapes.

**Comment by blampe** [comment]
How difficult would it be to write a script to re-write these shapes?

**Comment by prashantv** [comment]
Adding `GetFoo` functions that just return the struct field isn't very useful. However, Apache Thrift does do one thing in the `GetFoo` methods for optional fields -- it will return a non-pointer value, falling back to the default if the optional field was not set.

I'd like to have a plugin to add these on top, and users who are migrating services can opt in to the `IsFooSet` and `GetFoo` methods. Documenting the differences will also be really useful for services that are migrating.
