### ISSUE TITLE
Generate methods to get the value or the zero value for a field

### ISSUE THREAD

**Issue by azylman** [thriftrw/thriftrw-go#295]
In some of our code we don't need to distinguish between optional fields that are left out and the zero value for the type. It'd be nice if there were getters or something so we didn't need to define functions like this:

```go
func stringEmptyOrVal(x *string) string {
	if x == nil {
		return ""
	}
	return *x
}

func float64EmptyOrVal(x *float64) float64 {
	if x == nil {
		return 0
	}
	return *x
}

func int64EmptyOrVal(x *int64) int64 {
	if x == nil {
		return 0
	}
	return *x
}
```

**Comment by abhinav** [comment]
I was previously opposed to getters and setters because polluting the namespace seemed like a bad idea. However, now that we support `go.name` overrides for attributes, we can generate getter functions. Generating getters for only optional fields seems inconsistent. We'll probably want to generate them for all fields. Getters will also have to return the default values if a field was unset -- we already apply defaults at both, serialization and deserialization time.

Thoughts, @bombela @breerly?

**Comment by prashantv** [comment]
As long as we have a reasonable strategy for handling clashes (a struct with `get_age` and `age`), I think this is useful to do, especially to help migration from Apache Thrift to thriftrw.

We could make this optional via flags, but I think most services will probably want this.

**Comment by azylman** [comment]
These could also just be helper methods that are part of `thriftrw-go` or something, they don't have to be getters. Also, if they're helper methods, you don't need to worry about supporting them for non-primitives.

**Comment by abhinav** [comment]
RE: clashes: We support a `go.name` annotation now:

```thrift
struct MyStruct {
  1: optional int age
  2: optional int get_age
}
```

That will fail with an error about the `GetAge` attribute conflicting with the method `GetAge` so you have to use,

```thrift
struct MyStruct {
  1: optional int age
  2: optional int get_age (go.name = "GetAge2")
}
```
