### ISSUE TITLE
Add Context to request/response structs

### ISSUE THREAD

**Issue by dgrijalva** [thriftrw/thriftrw-go#344]
I'm trying to use this library with `net/rpc`. I've got something working, but the missing link is the ability to plumb my `context.Context` through for things like tracing. I was thinking a solution might be to add a property to the generated `X_Y_Args` structs. Is this possible to do? Via plugins maybe?

**Comment by abhinav** [comment]
Hello! Yes, that's exactly what the plugin system is for.

Originally, ThriftRW was going to generate the Client/Handler interfaces for
services but that would mean picking the exact set of arguments in ThriftRW
rather than whatever RPC library is using it. It would have to decide whether
context gets passed around as an argument and that can't be changed later.

In our RPC framework, for example, we have a `context.Context` as the first
argument and a trailing variadic argument of `Option`s like so,

    type Client interface {
        GetValue(context.Context, key string, options ...RPCOption) (*Value, error)
    }

Rather than making the decision in ThriftRW, we decided that the plugin system
would let the RPC layer decide what the interface looks like and handle
plumbing on that end.

The plugin API exists here: https://godoc.org/go.uber.org/thriftrw/plugin.
Documentation is a bit bare but the gist of it is that you need to implement
["plugin/api".ServiceGenerator][1] interface at some point. You'll receive a
structure that contains some information about the services for which code is
being generated and you will return the files to generate from that function.

For reference, you can find the plugin for our RPC system here: https://github.com/yarpc/yarpc-go/tree/master/encoding/thrift/thriftrw-plugin-yarpc.

  [1]: https://godoc.org/go.uber.org/thriftrw/plugin/api#ServiceGenerator

**Comment by abhinav** [comment]
Resolving this unless there are further questions.
