### ISSUE TITLE
plugin.Api GenerateServiceRequest should contain the thrift file path

### ISSUE THREAD

**Issue by DAddYE** [thriftrw/thriftrw-go#348]
Hi,

It would be amazing if the `api.GenerateServiceRequest` had a field containing the file path of its thrift file or a pointer to its original ast (not the api.Ast).

The reason for this is that for every `api.GenerateServiceRequest` I have to generate another thrift definition containing a subset of the service functions (using annotations).

**Comment by abhinav** [comment]
The API attempts to hide the actual file system away as much as possible. That
said, I see no problem with exposing the path to each Thrift file.

You wouldn't do it on GenerateServiceRequest, though, because one request can
include multiple Thrift files. This would probably be a new field on
[api.Module][1] which represents a single Thrift file.

I'll be happy to review a pull request if you implement this. I suggest
calling the new field `thriftFilePath`.

[1]: https://godoc.org/go.uber.org/thriftrw/plugin/api#Module
