### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#48]
We should consider implementing a strict mode at the library level that does this:
- If a field type is a mismatch, instead of ignoring it, fail the request.
- If a container's element type does not match what is expected from that container, fail the request.

(Update this issue with any other requirements that come up for strict mode.)

**Comment by prashantv** [comment]
I think we should be strict by default (at least in YARPC). Errors that this strict mode would catch would protect against backwards incompatible changes rather than ignoring the fields

cc @yarpc

**Comment by breerly** [comment]
Not a terrible idea - @abhinav what do you think?

**Comment by blampe** [comment]
Was this resolved by 785a6a0?

**Comment by abhinav** [comment]
No, that just adds non-strict mode to loosen up current thriftrw restrictions. Prashant is proposing adding a more strict mode.

**Comment by prashantv** [comment]
Our naming isn't great. There's 2 kinds of strict mode:
 - one for parsing of the Thrift file (which is what https://github.com/thriftrw/thriftrw-go/commit/785a6a01f441db024e5666df9ebff001ba50c13d lets you turn off)
 - one for parsing of bytes read on the wire (which is what this issue is about)

Right now, we're very lax when we receive binary payloads we don't expect, there's no warnings, or errors, but we just skip bad data. This means that when someone makes a backwards incompatible change is made by a service, it's not easily noticed (e.g. if they deploy a canary) since there's no errors or any way to track this. I think we should reject payloads instead so we catch these issues earlier.

**Comment by abhinav** [comment]
This is unlikely to happen unless someone makes a PR for it. I'm closing it
until future updates.
