### ISSUE TITLE
Infer go.tag from js.name annotation

### ISSUE THREAD

**Issue by kriskowal** [thriftrw/thriftrw-go#60]
thriftrw-node respects js.name to rename a field for the purpose of javascript and incidentally JSON. Presently, Go produces default `json:"name"` annotations for JSON serialization of Thrift structs. The default JSON name should be inferred from js.name. Presently, this would look like:

``` thrift
struct User {
    1: required string uuid (
        go.tag = 'json:"id",
        js.name = 'id'
     )
}

Which are redundant.
```

**Comment by abhinav** [comment]
Sounds good

**Comment by breerly** [comment]
I really think a bunch of `language:...` annotations is the wrong direction... :cry:

**Comment by abhinav** [comment]
Rather than infer this name from the js.name, we decided to support specifying
arbitrary tags with `go.tag`. Plus the newly added `go.label` gives you some
similar functionality. I think it's preferable that behavior of ThriftRW Go be
altered exclusively by annotations in the `go.*` namespace. Closing.
